from __future__ import annotations

COL_FECHA = "Fecha"
COL_DESC = "Descripcion"
COL_CONCEPTO = "Concepto"
COL_MONTO = "Monto"
COL_CATEGORIA = "Categoria"
COL_ESCENARIO = "Escenario"
COL_PROYECTO = "Proyecto"
COL_CLIENTE_ID = "ClienteID"
COL_CLIENTE_NOMBRE = "ClienteNombre"
COL_EMPRESA = "Empresa"
COL_POR_COBRAR = "Por_cobrar"
COL_COBRADO = "Cobrado"
COL_FECHA_COBRO = "Fecha de cobro"
COL_FECHA_REAL_COBRO = "Fecha real de cobro"
COL_RECURRENTE = "Recurrente"
COL_REC_PERIOD = "Periodo recurrencia"
COL_REC_RULE = "Regla fecha recurrencia"
COL_REC_DURATION = "Duracion recurrencia"
COL_REC_UNTIL = "Recurrencia hasta fecha"
COL_REC_COUNT = "Recurrencia cantidad periodos"
COL_ROW_ID = "RowID"
COL_USUARIO = "Usuario"

COL_POR_PAGAR = "Por_pagar"
COL_PROVEEDOR = "Proveedor"
COL_FECHA_PAGO = "Fecha esperada de pago"
COL_FECHA_REAL_PAGO = "Fecha real de pago"
COL_INGRESO_DETALLE = "Detalle ingreso"
COL_NATURALEZA_INGRESO = "Naturaleza ingreso"
COL_TRATAMIENTO_BALANCE_ING = "Tratamiento balance ingreso"
COL_TIPO_CONTRAPARTE = "Tipo contraparte"
COL_CONTRAPARTE = "Contraparte"
COL_MONTO_REAL_COBRADO = "Monto real cobrado"
COL_EVENTOS_PARCIALES_ING = "Detalle cobros parciales"
COL_FACTORING_DETALLE = "Detalle factoring"
COL_SUBCLASIFICACION_GERENCIAL = "Subclasificacion gerencial"
COL_GASTO_DETALLE = "Detalle gasto"
COL_TRATAMIENTO_BALANCE_GAS = "Tratamiento balance gasto"
COL_MONTO_REAL_PAGADO = "Monto real pagado"
COL_EVENTOS_PARCIALES_GAS = "Detalle pagos parciales"
COL_PREPAGO_MESES = "Plazo prepago meses"
COL_PREPAGO_FECHA_INICIO = "Fecha inicio prepago"
COL_INVENTARIO_MOVIMIENTO = "Movimiento inventario"
COL_INVENTARIO_ITEM = "Item inventario"
COL_INVENTARIO_FECHA_LLEGADA = "Fecha llegada inventario"
COL_ACTIVO_FIJO_TOGGLE = "Activo fijo"
COL_ACTIVO_FIJO_TIPO = "Tipo activo fijo"
COL_ACTIVO_FIJO_VIDA = "Vida util activo anios"
COL_ACTIVO_FIJO_FECHA_INICIO = "Fecha inicio activo"
COL_ACTIVO_FIJO_VALOR_RESIDUAL = "Valor residual activo"
COL_ACTIVO_FIJO_DEP_TOGGLE = "Depreciar amortizar"
COL_ACTIVO_FIJO_DEP_MENSUAL = "Depreciacion mensual"
COL_FINANCIAMIENTO_TOGGLE = "Financiamiento"
COL_FINANCIAMIENTO_TIPO = "Tipo financiamiento"
COL_FINANCIAMIENTO_MONTO = "Monto principal financiamiento"
COL_FINANCIAMIENTO_FECHA_INICIO = "Fecha inicio financiamiento"
COL_FINANCIAMIENTO_PLAZO = "Plazo financiamiento meses"
COL_FINANCIAMIENTO_TASA = "Tasa financiamiento"
COL_FINANCIAMIENTO_TASA_TIPO = "Tipo tasa financiamiento"
COL_FINANCIAMIENTO_MODALIDAD = "Modalidad financiamiento"
COL_FINANCIAMIENTO_PERIODICIDAD = "Periodicidad financiamiento"
COL_FINANCIAMIENTO_CRONOGRAMA = "Cronograma financiamiento"
COL_FINANCIAMIENTO_INSTRUMENTO = "Instrumento financiero"
COL_FINANCIAMIENTO_REG_TIPO = "Registro financiamiento"

INGRESOS_BASE_COLUMNS = [
    COL_FECHA,
    COL_DESC,
    COL_CONCEPTO,
    COL_MONTO,
    COL_CATEGORIA,
    COL_ESCENARIO,
    COL_PROYECTO,
    COL_CLIENTE_ID,
    COL_CLIENTE_NOMBRE,
    COL_EMPRESA,
    COL_POR_COBRAR,
    COL_COBRADO,
    COL_FECHA_COBRO,
    COL_FECHA_REAL_COBRO,
    COL_RECURRENTE,
    COL_REC_PERIOD,
    COL_REC_RULE,
    COL_REC_DURATION,
    COL_REC_UNTIL,
    COL_REC_COUNT,
    COL_INGRESO_DETALLE,
    COL_NATURALEZA_INGRESO,
    COL_TRATAMIENTO_BALANCE_ING,
    COL_TIPO_CONTRAPARTE,
    COL_CONTRAPARTE,
    COL_MONTO_REAL_COBRADO,
    COL_EVENTOS_PARCIALES_ING,
    COL_FACTORING_DETALLE,
    COL_FINANCIAMIENTO_TOGGLE,
    COL_FINANCIAMIENTO_TIPO,
    COL_FINANCIAMIENTO_MONTO,
    COL_FINANCIAMIENTO_FECHA_INICIO,
    COL_FINANCIAMIENTO_PLAZO,
    COL_FINANCIAMIENTO_TASA,
    COL_FINANCIAMIENTO_TASA_TIPO,
    COL_FINANCIAMIENTO_MODALIDAD,
    COL_FINANCIAMIENTO_PERIODICIDAD,
    COL_FINANCIAMIENTO_CRONOGRAMA,
    COL_FINANCIAMIENTO_INSTRUMENTO,
    COL_FINANCIAMIENTO_REG_TIPO,
    COL_ROW_ID,
    COL_USUARIO,
]

GASTOS_BASE_COLUMNS = [
    COL_FECHA,
    COL_DESC,
    COL_CONCEPTO,
    COL_MONTO,
    COL_CATEGORIA,
    COL_ESCENARIO,
    COL_PROYECTO,
    COL_CLIENTE_ID,
    COL_CLIENTE_NOMBRE,
    COL_EMPRESA,
    COL_POR_PAGAR,
    COL_PROVEEDOR,
    COL_RECURRENTE,
    COL_REC_PERIOD,
    COL_REC_RULE,
    COL_FECHA_PAGO,
    COL_FECHA_REAL_PAGO,
    COL_REC_DURATION,
    COL_REC_UNTIL,
    COL_REC_COUNT,
    COL_SUBCLASIFICACION_GERENCIAL,
    COL_GASTO_DETALLE,
    COL_TRATAMIENTO_BALANCE_GAS,
    COL_TIPO_CONTRAPARTE,
    COL_CONTRAPARTE,
    COL_MONTO_REAL_PAGADO,
    COL_EVENTOS_PARCIALES_GAS,
    COL_PREPAGO_MESES,
    COL_PREPAGO_FECHA_INICIO,
    COL_INVENTARIO_MOVIMIENTO,
    COL_INVENTARIO_ITEM,
    COL_INVENTARIO_FECHA_LLEGADA,
    COL_ACTIVO_FIJO_TOGGLE,
    COL_ACTIVO_FIJO_TIPO,
    COL_ACTIVO_FIJO_VIDA,
    COL_ACTIVO_FIJO_FECHA_INICIO,
    COL_ACTIVO_FIJO_VALOR_RESIDUAL,
    COL_ACTIVO_FIJO_DEP_TOGGLE,
    COL_ACTIVO_FIJO_DEP_MENSUAL,
    COL_FINANCIAMIENTO_TOGGLE,
    COL_FINANCIAMIENTO_TIPO,
    COL_FINANCIAMIENTO_MONTO,
    COL_FINANCIAMIENTO_FECHA_INICIO,
    COL_FINANCIAMIENTO_PLAZO,
    COL_FINANCIAMIENTO_TASA,
    COL_FINANCIAMIENTO_TASA_TIPO,
    COL_FINANCIAMIENTO_MODALIDAD,
    COL_FINANCIAMIENTO_PERIODICIDAD,
    COL_FINANCIAMIENTO_CRONOGRAMA,
    COL_FINANCIAMIENTO_INSTRUMENTO,
    COL_FINANCIAMIENTO_REG_TIPO,
    COL_ROW_ID,
    COL_USUARIO,
]

MISC_CATEGORY_ALIASES = {
    "miscelaneos",
    "miscelaneos.",
    "miscelaneo",
    "miscelaneo",
    "miscelaneos y otros",
    "miscelaneos/otros",
    "miscelaneos-otros",
    "misc",
    "miscellaneous",
    "miscel\u00e1neos",
    "miscel\u00e1neo",
}

COMISION_CATEGORY_ALIASES = {
    "comisiones",
    "comision",
    "comisi\u00f3n",
    "comisiones venta",
    "comisiones ventas",
}

EMPRESA_ALL_LABEL = "Todas"
